# This file was generated by GoReleaser. DO NOT EDIT.
cask "fflint" do
  name "fflint"
  desc "File formt linter"
  homepage "https://www.fflint.dev/"
  version "0.0.22"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fflint"
  manpage "manpages/fflint.1.gz"
  bash_completion "completions/fflint.bash"
  zsh_completion "completions/fflint.zsh"
  fish_completion "completions/fflint.fish"

  on_macos do
    on_intel do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Darwin_x86_64.tar.gz"
      sha256 "67e77b3574f1dbf664cf493a047021d6b7a5c629227314023aacb635a3685317"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Darwin_arm64.tar.gz"
      sha256 "71e06cfd6f9278c1d59c607d73e69b3dc32cbd0b0a1830da663cd6fe2c3ca203"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Linux_x86_64.tar.gz"
      sha256 "bc076d821726de2e2c8e32455cc1b95a5e533d36dc736d9ee360cc0e7fd3d67b"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Linux_arm64.tar.gz"
      sha256 "100ce9c39670da6e5be533d661e0cb4c6e7d9966bf6d7505ce0c49ea304dc5b4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fflint"]
    end
  end

  # No zap stanza required
end
