# This file was generated by GoReleaser. DO NOT EDIT.
cask "fflint" do
  name "fflint"
  desc "File formt linter"
  homepage "https://www.fflint.dev/"
  version "0.0.23"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fflint"
  manpage "manpages/fflint.1.gz"
  bash_completion "completions/fflint.bash"
  zsh_completion "completions/fflint.zsh"
  fish_completion "completions/fflint.fish"

  on_macos do
    on_intel do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Darwin_x86_64.tar.gz"
      sha256 "41c549733e193685a23666615242f3a33a2017dcd83de8a132c64c097567ee93"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Darwin_arm64.tar.gz"
      sha256 "e563abee2e67c093b54960c221157745a783f43296976d27385e2f3f4913fbea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Linux_x86_64.tar.gz"
      sha256 "58bbce9679cc2aafe25cb1e8b60d1c6c08669e0e5841bfa375997f6ed1ac6fda"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Linux_arm64.tar.gz"
      sha256 "1e4d4129eff90e1804c4d082769e26cebdfc768bb115406464d8a3cbd8198af6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fflint"]
    end
  end

  # No zap stanza required
end
