# This file was generated by GoReleaser. DO NOT EDIT.
cask "fflint" do
  name "fflint"
  desc "File formt linter"
  homepage "https://www.fflint.dev/"
  version "0.0.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fflint"
  bash_completion "completions/fflint.bash"
  zsh_completion "completions/fflint.zsh"
  fish_completion "completions/fflint.fish"

  on_macos do
    on_intel do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Darwin_x86_64.tar.gz"
      sha256 "08baccb65f702ea2a7e54a6463c0bb836ea0bedab7cc2f25d53a5345a5d43da8"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Darwin_arm64.tar.gz"
      sha256 "351411f4fdaf5ee21b0a1f58de49e3e9f7f174f4676bac552bc021289ed9e77e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Linux_x86_64.tar.gz"
      sha256 "8831aa83352165d98b6312255f40d4774fb25f48ae404ba1ba171529c6032874"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fflint/releases/download/v#{version}/fflint_Linux_arm64.tar.gz"
      sha256 "5b09a2d76d9e6ef8699bb7e5b6d7dcf19885e71cc3ce986b2f5f943afe9cd909"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fflint"]
    end
  end

  # No zap stanza required
end
