# This file was generated by GoReleaser. DO NOT EDIT.
cask "fftools" do
  name "fftools"
  desc "Utilities for analyzing, viewing and fixing file formats."
  homepage "https://tools.fileformat.info/"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asciify"
  binary "asciitable"
  binary "bytecount"
  binary "certinfo"
  binary "ghash"
  binary "hexdumpc"
  binary "hosty"
  binary "unhexdump"
  binary "unicount"
  binary "uniwhat"
  binary "urly"

  on_macos do
    on_intel do
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Darwin_x86_64.tar.gz"
      sha256 "fcc900d7d578269633d5ff2e735de416521d3f65fcca8b75084a4d6d8ffbc9ec"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Darwin_arm64.tar.gz"
      sha256 "ab239fdfc8310352671a1c8ec47523d60e119e547e69faa81ba450b572c1e5f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Linux_x86_64.tar.gz"
      sha256 "c63774f4942b42d703928db52912ccc2d0d61f9bcc52f8fc4a062f7b1ed7aff6"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Linux_arm64.tar.gz"
      sha256 "79303da4442ad30fbe70ef5e26f129acde48bb90cd3482797b6bd95fee347651"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/*"]
    end
  end

  # No zap stanza required
end
