# This file was generated by GoReleaser. DO NOT EDIT.
cask "fftools" do
  version "0.1.11"

  on_macos do
    on_intel do
      sha256 "8670a1a8f0892c4695734bd20cba069ba5c18c171eb0385555aef5ee2b618175"
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bbb816c21e8d1ceec65477493ee0939e3839c3f64b61e2b18a5e935be4f1021f"
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82a1b2322c216bc9aaf68eee62c28ab1e05a862b215c1cd4e0b7cfef4a565398"
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "34f9384885f5083d483cc43003e150fe3bf42ea2faae53b60e8e028dc901f75e"
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Linux_arm64.tar.gz"
    end
  end

  name "fftools"
  desc "Utilities for analyzing, viewing and fixing file formats."
  homepage "https://tools.fileformat.info/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asciify"
  binary "asciitable"
  binary "bytecount"
  binary "certinfo"
  binary "ghash"
  binary "hexdumpc"
  binary "hosty"
  binary "jsonfmt"
  binary "luhncheck"
  binary "luhngen"
  binary "unhexdump"
  binary "unicount"
  binary "uniwhat"
  binary "urly"
  binary "xmlfmt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/asciify"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/asciitable"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bytecount"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certinfo"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghash"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hexdumpc"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hosty"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jsonfmt"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/luhncheck"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/luhngen"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unhexdump"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unicount"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/uniwhat"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urly"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmlfmt"]
    end
  end

  # No zap stanza required

end
