# This file was generated by GoReleaser. DO NOT EDIT.
cask "fftools" do
  name "fftools"
  desc "Utilities for analyzing, viewing and fixing file formats."
  homepage "https://tools.fileformat.info/"
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asciify"
  binary "asciitable"
  binary "bytecount"
  binary "certinfo"
  binary "ghash"
  binary "hexdumpc"
  binary "hosty"
  binary "jsonfmt"
  binary "luhncheck"
  binary "luhngen"
  binary "unhexdump"
  binary "unicount"
  binary "uniwhat"
  binary "urly"

  on_macos do
    on_intel do
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Darwin_x86_64.tar.gz"
      sha256 "6f4eb97666af525ff2f060751d852ada71c30c646eff00b3b5ea8947128a1319"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Darwin_arm64.tar.gz"
      sha256 "3bea23caead5872c9cfc9be0fd54fb6a6d34d1bd5fae9ca8382369f5589ffc61"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Linux_x86_64.tar.gz"
      sha256 "b83ea2aefe144e131e6027bbc187c460a8bebd7c8464a4bb0697ec34a7c13e93"
    end
    on_arm do
      url "https://github.com/FileFormatInfo/fftools/releases/download/#{version}/fftools_Linux_arm64.tar.gz"
      sha256 "6bf2a8e9b74d38bb05f8f5e8312a6f3fff3fe9b6ef2e093441932b8106aa2775"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/asciify"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/asciitable"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bytecount"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certinfo"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghash"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hexdumpc"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hosty"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jsonfmt"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/luhncheck"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/luhngen"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unhexdump"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unicount"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/uniwhat"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urly"]
    end
  end

  # No zap stanza required
end
